In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import ast

In [16]:
df = pd.read_csv('../results/zooid/lcl_cc_rf.csv')
df['true_vector'] = df['true_vector'].apply(ast.literal_eval)
df['true_vector'] = df['true_vector'].apply(lambda x: np.array(x))

df['pred_vector'] = df['pred_vector'].apply(ast.literal_eval)
df['pred_vector'] = df['pred_vector'].apply(lambda x: np.array(x))

df.head()

,bag_idx,nodes_order,true_vector,pred_vector,absolute_error,quantifier,classifier,strategy
0,0,"[""Root"", ""Root.Phylum_Annelida"", ""Root.Phylum_...","[1.0, 0.025, 0.025, 0.425, 0.425, 0.03, 0.03, ...","[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.145690,cc,rf,lcl
1,1,"[""Root"", ""Root.Phylum_Annelida"", ""Root.Phylum_...","[1.0, 0.325, 0.325, 0.275, 0.275, 0.055, 0.055...","[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.110345,cc,rf,lcl
2,2,"[""Root"", ""Root.Phylum_Annelida"", ""Root.Phylum_...","[1.0, 0.155, 0.155, 0.425, 0.425, 0.17, 0.17, ...","[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.138621,cc,rf,lcl
3,3,"[""Root"", ""Root.Phylum_Annelida"", ""Root.Phylum_...","[1.0, 0.025, 0.025, 0.18, 0.18, 0.125, 0.125, ...","[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.149483,cc,rf,lcl
4,4,"[""Root"", ""Root.Phylum_Annelida"", ""Root.Phylum_...","[1.0, 0.0, 0.0, 0.45, 0.45, 0.195, 0.195, 0.19...","[1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",0.150690,cc,rf,lcl

In [ ]:
df.true_vector.values[0].sum()

np.float64(4.315)

:

In [20]:

(df.true_vector.values[0] - df.pred_vector.values[0]).sum()

np.float64(2.3150000000000004)

In [18]:
df.pred_vector.values[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
df = pd.read_parquet('../data/multi-class/zooid/full.parquet')
df.head()

,id,embeddings,label
0,1,"[0.13995885848999023, -0.05522964894771576, -0...",Phylum_Chordata.Subphylum_Vertebrata.Class_Ost...
1,2,"[0.13995885848999023, -0.05522964894771576, -0...",Phylum_Chordata.Subphylum_Vertebrata.Class_Ost...
2,3,"[0.13995885848999023, -0.05522964894771576, -0...",Phylum_Chordata.Subphylum_Vertebrata.Class_Ost...
3,4,"[0.13995885848999023, -0.05522964894771576, -0...",Phylum_Chordata.Subphylum_Vertebrata.Class_Ost...
4,5,"[0.13995885848999023, -0.05522964894771576, -0...",Phylum_Chordata.Subphylum_Vertebrata.Class_Ost...

In [9]:
train_df, test_df = train_test_split(
  df,
  test_size=0.5, 
  random_state=42, 
  stratify=df['label']
)

train_df.to_parquet('../data/multi-class/zooid/train.parquet', engine='pyarrow')
test_df.to_parquet('../data/multi-class/zooid/test.parquet', engine='pyarrow')

In [7]:
train_df.label.value_counts()

label
Phylum_Chaetognata                                                                                                         86
Phylum_Ctenophora                                                                                                          60
Phylum_Mollusca.Class_Gastropoda.Superfamily_Pterotracheoidea                                                              43
Phylum_Arthropoda.Subphylum_Crustacea.Class_Maxillopoda.Subclass_Cirripedia                                                20
Phylum_Mollusca.Class_Gastropoda.Order_Pteropoda                                                                           20
Phylum_Chordata.Subphylum_Vertebrata.Class_Osteichthyes                                                                    15
Phylum_Cnidaria.Subphylum_Medusozoa.Class_Hydrozoa                                                                         14
Phylum_Arthropoda.Subphylum_Crustacea.Class_Malacostraca.Subclass_Eumalacostraca.Superorder_Eucarida.Order_Decapoda        12
Phylum_Chordata.Subphylum_Tunicata.Class_Thaliacea.Order_Salpida                                                            8
Phylum_Chordata.Subphylum_Tunicata.Class_Appendicularia                                                                     8
Phylum_Annelida.Class_Polychaeta                                                                                            6
Phylum_Arthropoda.Subphylum_Crustacea.Class_Malacostraca.Subclass_Eumalacostraca.Superorder_Eucarida.Order_Euphausiacea     5
Phylum_Arthropoda.Subphylum_Crustacea.Class_Ostracoda                                                                       2
Name: count, dtype: int64

In [8]:
test_df.label.value_counts()

label
Phylum_Chaetognata                                                                                                         87
Phylum_Ctenophora                                                                                                          60
Phylum_Mollusca.Class_Gastropoda.Superfamily_Pterotracheoidea                                                              44
Phylum_Mollusca.Class_Gastropoda.Order_Pteropoda                                                                           20
Phylum_Arthropoda.Subphylum_Crustacea.Class_Maxillopoda.Subclass_Cirripedia                                                20
Phylum_Chordata.Subphylum_Vertebrata.Class_Osteichthyes                                                                    14
Phylum_Cnidaria.Subphylum_Medusozoa.Class_Hydrozoa                                                                         14
Phylum_Arthropoda.Subphylum_Crustacea.Class_Malacostraca.Subclass_Eumalacostraca.Superorder_Eucarida.Order_Decapoda        13
Phylum_Chordata.Subphylum_Tunicata.Class_Thaliacea.Order_Salpida                                                            9
Phylum_Chordata.Subphylum_Tunicata.Class_Appendicularia                                                                     7
Phylum_Arthropoda.Subphylum_Crustacea.Class_Malacostraca.Subclass_Eumalacostraca.Superorder_Eucarida.Order_Euphausiacea     5
Phylum_Annelida.Class_Polychaeta                                                                                            5
Phylum_Arthropoda.Subphylum_Crustacea.Class_Ostracoda                                                                       1
Name: count, dtype: int64

In [10]:
# Root -> l1 -> l2 -> l3
print(f'Nodes on Level 1: {len(np.unique(dbpedia_train.l1))}')
print(f'Nodes on Level 2: {len(np.unique(dbpedia_train.l2))}')
print(f'Nodes on Level 3: {len(np.unique(dbpedia_train.l3))}')

Nodes on Level 1: 9
Nodes on Level 2: 70
Nodes on Level 3: 219

In [12]:
amazonh = pd.read_csv('../data/amazonh/train_40k.csv')
amazonh.head()

,productId,Title,userId,Helpfulness,Score,Time,Text,Cat1,Cat2,Cat3
0,B000E46LYG,Golden Valley Natural Buffalo Jerky,A3MQDNGHDJU4MK,0/0,3.0,-1,The description and photo on this product need...,grocery gourmet food,meat poultry,jerky
1,B000GRA6N8,Westing Game,unknown,0/0,5.0,860630400,This was a great book!!!! It is well thought t...,toys games,games,unknown
2,B000GRA6N8,Westing Game,unknown,0/0,5.0,883008000,"I am a first year teacher, teaching 5th grade....",toys games,games,unknown
3,B000GRA6N8,Westing Game,unknown,0/0,5.0,897696000,I got the book at my bookfair at school lookin...,toys games,games,unknown
4,B00000DMDQ,I SPY A is For Jigsaw Puzzle 63pc,unknown,2/4,5.0,911865600,Hi! I'm Martine Redman and I created this puzz...,toys games,puzzles,jigsaw puzzles

In [13]:
# Root -> cat1 -> cat2 -> cat3
print(f'Nodes on Level 1: {len(np.unique(amazonh.Cat1))}')
print(f'Nodes on Level 2: {len(np.unique(amazonh.Cat2))}')
print(f'Nodes on Level 3: {len(np.unique(amazonh.Cat3))}')

Nodes on Level 1: 6
Nodes on Level 2: 64
Nodes on Level 3: 464

In [16]:
olid = pd.read_csv('../data/olid/olid-training-v1.0.tsv', sep='/t', encoding='utf-8')
olid.head()

/tmp/ipykernel_2871015/3196503451.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  olid = pd.read_csv('../data/olid/olid-training-v1.0.tsv', sep='/t', encoding='utf-8')

ParserError: Expected 1 fields in line 39, saw 2. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.