In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_parquet('../data/multi-label/church/train.parquet')
df.head()

,chip_affymetrix_chip,pp_number_of_probe_pairs,a_fy4_a,alpha_fy5_alpha,gal_gal,heat_heat,rel_alpha_fy5_alpha,rel_gal_gal,rel_heat_heat,avg_abund,...,thrshld_1=below_detection_fy4_a,thrshld_1=below_detection_fy5_alpha,thrshld_1=below_detection_gal,thrshld_1=below_detection_heat,thrshld_gal,thrshld_fy5_alpha,thrshld_heat,below_threshold_in_all_conditions,target_labels,labels_list
0,B,21.0,0.10,3.67,0.10,0.10,1.22,0.00,0.00,0.97,...,1.0,NaN,1.0,1.0,5.0,2.0,5.0,0.0,"[34, 30/05, 34/11/03/07, 30, 34/11/03, 34/11]","[34, 30/05, 34/11/03/07, 30, 34/11/03, 34/11]"
1,A,20.0,0.10,0.51,0.10,0.10,0.67,0.00,0.00,0.19,...,1.0,NaN,1.0,1.0,5.0,2.0,5.0,0.0,"[11/02, 34, 18/02, 41/01, 11/02/03, 34/11/03/0...","[11/02, 34, 18/02, 41/01, 11/02/03, 34/11/03/0..."
2,A,20.0,0.10,0.37,0.10,0.10,0.63,0.00,0.00,0.16,...,1.0,NaN,1.0,1.0,5.0,2.0,5.0,0.0,"[11/02, 34, 18/02, 41/01, 11/02/03, 34/11/03/0...","[11/02, 34, 18/02, 41/01, 11/02/03, 34/11/03/0..."
3,C,21.0,0.40,1.74,0.30,0.20,0.48,0.00,0.00,0.65,...,1.0,NaN,1.0,1.0,5.0,NaN,5.0,0.0,"[34, 16, 41/01, 16/01, 34/11/03/07, 34/11/03, ...","[34, 16, 41/01, 16/01, 34/11/03/07, 34/11/03, ..."
4,B,21.0,0.44,1.09,0.48,0.69,0.38,0.14,0.15,0.68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"[16, 01/03/04/03, 16/19, 01/03, 01/03/04, 01]","[16, 01/03/04/03, 16/19, 01/03, 01/03/04, 01]"

In [ ]:
df.()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1628 entries, 0 to 1627
Columns: 532 entries, cln3-1 to 99
dtypes: float64(77), object(1), uint8(454)
memory usage: 1.7+ MB

In [10]:
# Root -> l1 -> l2 -> l3
print(f'Nodes on Level 1: {len(np.unique(dbpedia_train.l1))}')
print(f'Nodes on Level 2: {len(np.unique(dbpedia_train.l2))}')
print(f'Nodes on Level 3: {len(np.unique(dbpedia_train.l3))}')

Nodes on Level 1: 9
Nodes on Level 2: 70
Nodes on Level 3: 219

In [12]:
amazonh = pd.read_csv('../data/amazonh/train_40k.csv')
amazonh.head()

,productId,Title,userId,Helpfulness,Score,Time,Text,Cat1,Cat2,Cat3
0,B000E46LYG,Golden Valley Natural Buffalo Jerky,A3MQDNGHDJU4MK,0/0,3.0,-1,The description and photo on this product need...,grocery gourmet food,meat poultry,jerky
1,B000GRA6N8,Westing Game,unknown,0/0,5.0,860630400,This was a great book!!!! It is well thought t...,toys games,games,unknown
2,B000GRA6N8,Westing Game,unknown,0/0,5.0,883008000,"I am a first year teacher, teaching 5th grade....",toys games,games,unknown
3,B000GRA6N8,Westing Game,unknown,0/0,5.0,897696000,I got the book at my bookfair at school lookin...,toys games,games,unknown
4,B00000DMDQ,I SPY A is For Jigsaw Puzzle 63pc,unknown,2/4,5.0,911865600,Hi! I'm Martine Redman and I created this puzz...,toys games,puzzles,jigsaw puzzles

In [13]:
# Root -> cat1 -> cat2 -> cat3
print(f'Nodes on Level 1: {len(np.unique(amazonh.Cat1))}')
print(f'Nodes on Level 2: {len(np.unique(amazonh.Cat2))}')
print(f'Nodes on Level 3: {len(np.unique(amazonh.Cat3))}')

Nodes on Level 1: 6
Nodes on Level 2: 64
Nodes on Level 3: 464

In [16]:
olid = pd.read_csv('../data/olid/olid-training-v1.0.tsv', sep='/t', encoding='utf-8')
olid.head()

/tmp/ipykernel_2871015/3196503451.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  olid = pd.read_csv('../data/olid/olid-training-v1.0.tsv', sep='/t', encoding='utf-8')

ParserError: Expected 1 fields in line 39, saw 2. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.