In [4]:
import pandas as pd
import numpy as np

In [3]:
dbpedia_train = pd.read_csv('../data/dbpedia/DBPEDIA_train.csv')
dbpedia_train.head()

,text,l1,l2,l3
0,"William Alexander Massey (October 7, 1856 – Ma...",Agent,Politician,Senator
1,Lions is the sixth studio album by American ro...,Work,MusicalWork,Album
2,"Pirqa (Aymara and Quechua for wall, hispaniciz...",Place,NaturalPlace,Mountain
3,Cancer Prevention Research is a biweekly peer-...,Work,PeriodicalLiterature,AcademicJournal
4,The Princeton University Chapel is located on ...,Place,Building,HistoricBuilding

In [10]:
# Root -> l1 -> l2 -> l3
print(f'Nodes on Level 1: {len(np.unique(dbpedia_train.l1))}')
print(f'Nodes on Level 2: {len(np.unique(dbpedia_train.l2))}')
print(f'Nodes on Level 3: {len(np.unique(dbpedia_train.l3))}')

Nodes on Level 1: 9
Nodes on Level 2: 70
Nodes on Level 3: 219

In [12]:
amazonh = pd.read_csv('../data/amazonh/train_40k.csv')
amazonh.head()

,productId,Title,userId,Helpfulness,Score,Time,Text,Cat1,Cat2,Cat3
0,B000E46LYG,Golden Valley Natural Buffalo Jerky,A3MQDNGHDJU4MK,0/0,3.0,-1,The description and photo on this product need...,grocery gourmet food,meat poultry,jerky
1,B000GRA6N8,Westing Game,unknown,0/0,5.0,860630400,This was a great book!!!! It is well thought t...,toys games,games,unknown
2,B000GRA6N8,Westing Game,unknown,0/0,5.0,883008000,"I am a first year teacher, teaching 5th grade....",toys games,games,unknown
3,B000GRA6N8,Westing Game,unknown,0/0,5.0,897696000,I got the book at my bookfair at school lookin...,toys games,games,unknown
4,B00000DMDQ,I SPY A is For Jigsaw Puzzle 63pc,unknown,2/4,5.0,911865600,Hi! I'm Martine Redman and I created this puzz...,toys games,puzzles,jigsaw puzzles

In [13]:
# Root -> cat1 -> cat2 -> cat3
print(f'Nodes on Level 1: {len(np.unique(amazonh.Cat1))}')
print(f'Nodes on Level 2: {len(np.unique(amazonh.Cat2))}')
print(f'Nodes on Level 3: {len(np.unique(amazonh.Cat3))}')

Nodes on Level 1: 6
Nodes on Level 2: 64
Nodes on Level 3: 464

In [16]:
olid = pd.read_csv('../data/olid/olid-training-v1.0.tsv', sep='/t', encoding='utf-8')
olid.head()

/tmp/ipykernel_2871015/3196503451.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  olid = pd.read_csv('../data/olid/olid-training-v1.0.tsv', sep='/t', encoding='utf-8')

ParserError: Expected 1 fields in line 39, saw 2. Error could possibly be due to quotes being ignored when a multi-char delimiter is used.