In [28]:
import pandas as pd
import ast
import numpy as np
import re

def limpar_e_converter(texto):
    # 1. Remove 'np.float64(' mas mantém o número
    # O \d+\.?\d* captura o número (inteiro ou decimal)
    texto_limpo = re.sub(r'np\.float64\((.*?)\)', r'\1', texto)
    
    # 2. Agora a string é uma tupla Python válida: ({1: 0.66, ...}, 1.24)
    return ast.literal_eval(texto_limpo)

In [31]:
dbpedia = pd.read_csv('../results/dbpedia/lql.csv')

In [32]:
dbpedia = pd.read_csv('../results/dbpedia/lql.csv')
dbpedia['hae'] = dbpedia['hae'].apply(limpar_e_converter)

hae_split = pd.DataFrame(dbpedia['hae'].tolist(), index=dbpedia.index)
hae_split.columns = ['hae_level', 'hae_total']

dbpedia = pd.concat([dbpedia, hae_split], axis=1).drop(columns=['hae'])

dbpedia.head()

,bag_idx,true_prevalences,pred_prevalences,quantifier,classifier,strategy,hae_level,hae_total
0,0,"{""Place"": 0.13, ""Species"": 0.075, ""Event"": 0.0...","{""Agent"": 0.695, ""Device"": 0.0, ""Event"": 0.085...",cc,rf,LQL,"{1: 0.15999999999999998, 2: 0.4870548871626456...",0.460113
1,1,"{""Work"": 0.075, ""Agent"": 0.58, ""Species"": 0.06...","{""Agent"": 0.655, ""Device"": 0.0, ""Event"": 0.065...",cc,rf,LQL,"{1: 0.15000000000000008, 2: 0.4880196553197550...",0.485629
2,2,"{""Place"": 0.2, ""Species"": 0.07, ""Agent"": 0.605...","{""Agent"": 0.69, ""Device"": 0.0, ""Event"": 0.05, ...",cc,rf,LQL,"{1: 0.18, 2: 0.439501287001287, 3: 0.761667350...",0.460390
3,3,"{""Agent"": 0.62, ""Place"": 0.095, ""Work"": 0.08, ...","{""Agent"": 0.665, ""Device"": 0.0, ""Event"": 0.09,...",cc,rf,LQL,"{1: 0.11000000000000004, 2: 0.5035975409836065...",0.477432
4,4,"{""Agent"": 0.595, ""SportsSeason"": 0.015, ""Place...","{""Agent"": 0.65, ""Device"": 0.0, ""Event"": 0.06, ...",cc,rf,LQL,"{1: 0.11000000000000004, 2: 0.5655669140020285...",0.540944

In [33]:
dbpedia[['hae_total', 'quantifier', 'classifier']].groupby(by=['quantifier', 'classifier']).mean()

                       hae_total
quantifier classifier
ac         rf           0.522814
cc         rf           0.522814
dfy        rf           1.044943
hdy        rf           1.044943
pac        rf           0.579957
pcc        rf           0.629496